language: java
jdk:
- oraclejdk8

env:
  - MAVEN_VERSION=4.0.0
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "mvn test"